#!/usr/bin/python
# -*- coding: utf-8 -*-

"""test foreground and background colors"""

from colored import fore, back, style


def main():

    print fore.BLACK + "Hello World !!!" + style.RESET
    print fore.RED + "Hello World !!!" + style.RESET
    print fore.GREEN + "Hello World !!!" + style.RESET
    print fore.YELLOW + "Hello World !!!" + style.RESET
    print fore.BLUE + "Hello World !!!" + style.RESET
    print fore.MAGENTA + "Hello World !!!" + style.RESET
    print fore.CYAN + "Hello World !!!" + style.RESET
    print fore.LIGHT_GRAY + "Hello World !!!" + style.RESET
    print fore.DARK_GRAY + "Hello World !!!" + style.RESET
    print fore.LIGHT_RED + "Hello World !!!" + style.RESET
    print fore.LIGHT_GREEN + "Hello World !!!" + style.RESET
    print fore.LIGHT_YELLOW + "Hello World !!!" + style.RESET
    print fore.LIGHT_BLUE + "Hello World !!!" + style.RESET
    print fore.LIGHT_MAGENTA + "Hello World !!!" + style.RESET
    print fore.LIGHT_CYAN + "Hello World !!!" + style.RESET
    print fore.WHITE + "Hello World !!!" + style.RESET
    print fore.GREY_0 + "Hello World !!!" + style.RESET
    print fore.NAVY_BLUE + "Hello World !!!" + style.RESET
    print fore.DARK_BLUE + "Hello World !!!" + style.RESET
    print fore.BLUE_3A + "Hello World !!!" + style.RESET
    print fore.BLUE_3B + "Hello World !!!" + style.RESET
    print fore.BLUE_1 + "Hello World !!!" + style.RESET
    print fore.DARK_GREEN + "Hello World !!!" + style.RESET
    print fore.DEEP_SKY_BLUE_4A + "Hello World !!!" + style.RESET
    print fore.DEEP_SKY_BLUE_4B + "Hello World !!!" + style.RESET
    print fore.DEEP_SKY_BLUE_4C + "Hello World !!!" + style.RESET
    print fore.DODGER_BLUE_3 + "Hello World !!!" + style.RESET
    print fore.DODGER_BLUE_2 + "Hello World !!!" + style.RESET
    print fore.GREEN_4 + "Hello World !!!" + style.RESET
    print fore.SPRING_GREEN_4 + "Hello World !!!" + style.RESET
    print fore.TURQUOISE_4 + "Hello World !!!" + style.RESET
    print fore.DEEP_SKY_BLUE_3A + "Hello World !!!" + style.RESET
    print fore.DEEP_SKY_BLUE_3B + "Hello World !!!" + style.RESET
    print fore.DODGER_BLUE_1 + "Hello World !!!" + style.RESET
    print fore.GREEN_3A + "Hello World !!!" + style.RESET
    print fore.SPRING_GREEN_3A + "Hello World !!!" + style.RESET
    print fore.DARK_CYAN + "Hello World !!!" + style.RESET
    print fore.LIGHT_SEA_GREEN + "Hello World !!!" + style.RESET
    print fore.DEEP_SKY_BLUE_2 + "Hello World !!!" + style.RESET
    print fore.DEEP_SKY_BLUE_1 + "Hello World !!!" + style.RESET
    print fore.GREEN_3B + "Hello World !!!" + style.RESET
    print fore.SPRING_GREEN_3B + "Hello World !!!" + style.RESET
    print fore.SPRING_GREEN_2A + "Hello World !!!" + style.RESET
    print fore.CYAN_3 + "Hello World !!!" + style.RESET
    print fore.DARK_TURQUOISE + "Hello World !!!" + style.RESET
    print fore.TURQUOISE_2 + "Hello World !!!" + style.RESET
    print fore.GREEN_1 + "Hello World !!!" + style.RESET
    print fore.SPRING_GREEN_2B + "Hello World !!!" + style.RESET
    print fore.SPRING_GREEN_1 + "Hello World !!!" + style.RESET
    print fore.MEDIUM_SPRING_GREEN + "Hello World !!!" + style.RESET
    print fore.CYAN_2 + "Hello World !!!" + style.RESET
    print fore.CYAN_1 + "Hello World !!!" + style.RESET
    print fore.DARK_RED_1 + "Hello World !!!" + style.RESET
    print fore.DEEP_PINK_4A + "Hello World !!!" + style.RESET
    print fore.PURPLE_4A + "Hello World !!!" + style.RESET
    print fore.PURPLE_4B + "Hello World !!!" + style.RESET
    print fore.PURPLE_3 + "Hello World !!!" + style.RESET
    print fore.BLUE_VIOLET + "Hello World !!!" + style.RESET
    print fore.ORANGE_4A + "Hello World !!!" + style.RESET
    print fore.GREY_37 + "Hello World !!!" + style.RESET
    print fore.MEDIUM_PURPLE_4 + "Hello World !!!" + style.RESET
    print fore.SLATE_BLUE_3A + "Hello World !!!" + style.RESET
    print fore.SLATE_BLUE_3B + "Hello World !!!" + style.RESET
    print fore.ROYAL_BLUE_1 + "Hello World !!!" + style.RESET
    print fore.CHARTREUSE_4 + "Hello World !!!" + style.RESET
    print fore.DARK_SEA_GREEN_4A + "Hello World !!!" + style.RESET
    print fore.PALE_TURQUOISE_4 + "Hello World !!!" + style.RESET
    print fore.STEEL_BLUE + "Hello World !!!" + style.RESET
    print fore.STEEL_BLUE_3 + "Hello World !!!" + style.RESET
    print fore.CORNFLOWER_BLUE + "Hello World !!!" + style.RESET
    print fore.CHARTREUSE_3A + "Hello World !!!" + style.RESET
    print fore.DARK_SEA_GREEN_4B + "Hello World !!!" + style.RESET
    print fore.CADET_BLUE_2 + "Hello World !!!" + style.RESET
    print fore.CADET_BLUE_1 + "Hello World !!!" + style.RESET
    print fore.SKY_BLUE_3 + "Hello World !!!" + style.RESET
    print fore.STEEL_BLUE_1A + "Hello World !!!" + style.RESET
    print fore.CHARTREUSE_3B + "Hello World !!!" + style.RESET
    print fore.PALE_GREEN_3A + "Hello World !!!" + style.RESET
    print fore.SEA_GREEN_3 + "Hello World !!!" + style.RESET
    print fore.AQUAMARINE_3 + "Hello World !!!" + style.RESET
    print fore.MEDIUM_TURQUOISE + "Hello World !!!" + style.RESET
    print fore.STEEL_BLUE_1B + "Hello World !!!" + style.RESET
    print fore.CHARTREUSE_2A + "Hello World !!!" + style.RESET
    print fore.SEA_GREEN_2 + "Hello World !!!" + style.RESET
    print fore.SEA_GREEN_1A + "Hello World !!!" + style.RESET
    print fore.SEA_GREEN_1B + "Hello World !!!" + style.RESET
    print fore.AQUAMARINE_1A + "Hello World !!!" + style.RESET
    print fore.DARK_SLATE_GRAY_2 + "Hello World !!!" + style.RESET
    print fore.DARK_RED_2 + "Hello World !!!" + style.RESET
    print fore.DEEP_PINK_4B + "Hello World !!!" + style.RESET
    print fore.DARK_MAGENTA_1 + "Hello World !!!" + style.RESET
    print fore.DARK_MAGENTA_2 + "Hello World !!!" + style.RESET
    print fore.DARK_VIOLET_1A + "Hello World !!!" + style.RESET
    print fore.PURPLE_1A + "Hello World !!!" + style.RESET
    print fore.ORANGE_4B + "Hello World !!!" + style.RESET
    print fore.LIGHT_PINK_4 + "Hello World !!!" + style.RESET
    print fore.PLUM_4 + "Hello World !!!" + style.RESET
    print fore.MEDIUM_PURPLE_3A + "Hello World !!!" + style.RESET
    print fore.MEDIUM_PURPLE_3B + "Hello World !!!" + style.RESET
    print fore.SLATE_BLUE_1 + "Hello World !!!" + style.RESET
    print fore.YELLOW_4A + "Hello World !!!" + style.RESET
    print fore.WHEAT_4 + "Hello World !!!" + style.RESET
    print fore.GREY_53 + "Hello World !!!" + style.RESET
    print fore.LIGHT_SLATE_GREY + "Hello World !!!" + style.RESET
    print fore.MEDIUM_PURPLE + "Hello World !!!" + style.RESET
    print fore.LIGHT_SLATE_BLUE + "Hello World !!!" + style.RESET
    print fore.YELLOW_4B + "Hello World !!!" + style.RESET
    print fore.DARK_OLIVE_GREEN_3A + "Hello World !!!" + style.RESET
    print fore.DARK_GREEN_SEA + "Hello World !!!" + style.RESET
    print fore.LIGHT_SKY_BLUE_3A + "Hello World !!!" + style.RESET
    print fore.LIGHT_SKY_BLUE_3B + "Hello World !!!" + style.RESET
    print fore.SKY_BLUE_2 + "Hello World !!!" + style.RESET
    print fore.CHARTREUSE_2B + "Hello World !!!" + style.RESET
    print fore.DARK_OLIVE_GREEN_3B + "Hello World !!!" + style.RESET
    print fore.PALE_GREEN_3B + "Hello World !!!" + style.RESET
    print fore.DARK_SEA_GREEN_3A + "Hello World !!!" + style.RESET
    print fore.DARK_SLATE_GRAY_3 + "Hello World !!!" + style.RESET
    print fore.SKY_BLUE_1 + "Hello World !!!" + style.RESET
    print fore.CHARTREUSE_1 + "Hello World !!!" + style.RESET
    print fore.LIGHT_GREEN_2 + "Hello World !!!" + style.RESET
    print fore.LIGHT_GREEN_3 + "Hello World !!!" + style.RESET
    print fore.PALE_GREEN_1A + "Hello World !!!" + style.RESET
    print fore.AQUAMARINE_1B + "Hello World !!!" + style.RESET
    print fore.DARK_SLATE_GRAY_1 + "Hello World !!!" + style.RESET
    print fore.RED_3A + "Hello World !!!" + style.RESET
    print fore.DEEP_PINK_4C + "Hello World !!!" + style.RESET
    print fore.MEDIUM_VIOLET_RED + "Hello World !!!" + style.RESET
    print fore.MAGENTA_3A + "Hello World !!!" + style.RESET
    print fore.DARK_VIOLET_1B + "Hello World !!!" + style.RESET
    print fore.PURPLE_1B + "Hello World !!!" + style.RESET
    print fore.DARK_ORANGE_3A + "Hello World !!!" + style.RESET
    print fore.INDIAN_RED_1A + "Hello World !!!" + style.RESET
    print fore.HOT_PINK_3A + "Hello World !!!" + style.RESET
    print fore.MEDIUM_ORCHID_3 + "Hello World !!!" + style.RESET
    print fore.MEDIUM_ORCHID + "Hello World !!!" + style.RESET
    print fore.MEDIUM_PURPLE_2A + "Hello World !!!" + style.RESET
    print fore.DARK_GOLDENROD + "Hello World !!!" + style.RESET
    print fore.LIGHT_SALMON_3A + "Hello World !!!" + style.RESET
    print fore.ROSY_BROWN + "Hello World !!!" + style.RESET
    print fore.GREY_63 + "Hello World !!!" + style.RESET
    print fore.MEDIUM_PURPLE_2B + "Hello World !!!" + style.RESET
    print fore.MEDIUM_PURPLE_1 + "Hello World !!!" + style.RESET
    print fore.GOLD_3A + "Hello World !!!" + style.RESET
    print fore.DARK_KHAKI + "Hello World !!!" + style.RESET
    print fore.NAVAJO_WHITE_3 + "Hello World !!!" + style.RESET
    print fore.GREY_69 + "Hello World !!!" + style.RESET
    print fore.LIGHT_STEEL_BLUE_3 + "Hello World !!!" + style.RESET
    print fore.LIGHT_STEEL_BLUE + "Hello World !!!" + style.RESET
    print fore.YELLOW_3A + "Hello World !!!" + style.RESET
    print fore.DARK_OLIVE_GREEN_3 + "Hello World !!!" + style.RESET
    print fore.DARK_SEA_GREEN_3B + "Hello World !!!" + style.RESET
    print fore.DARK_SEA_GREEN_2 + "Hello World !!!" + style.RESET
    print fore.LIGHT_CYAN_3 + "Hello World !!!" + style.RESET
    print fore.LIGHT_SKY_BLUE_1 + "Hello World !!!" + style.RESET
    print fore.GREEN_YELLOW + "Hello World !!!" + style.RESET
    print fore.DARK_OLIVE_GREEN_2 + "Hello World !!!" + style.RESET
    print fore.PALE_GREEN_1B + "Hello World !!!" + style.RESET
    print fore.DARK_SEA_GREEN_5B + "Hello World !!!" + style.RESET
    print fore.DARK_SEA_GREEN_5A + "Hello World !!!" + style.RESET
    print fore.PALE_TURQUOISE_1 + "Hello World !!!" + style.RESET
    print fore.RED_3B + "Hello World !!!" + style.RESET
    print fore.DEEP_PINK_3A + "Hello World !!!" + style.RESET
    print fore.DEEP_PINK_3B + "Hello World !!!" + style.RESET
    print fore.MAGENTA_3B + "Hello World !!!" + style.RESET
    print fore.MAGENTA_3C + "Hello World !!!" + style.RESET
    print fore.MAGENTA_2A + "Hello World !!!" + style.RESET
    print fore.DARK_ORANGE_3B + "Hello World !!!" + style.RESET
    print fore.INDIAN_RED_1B + "Hello World !!!" + style.RESET
    print fore.HOT_PINK_3B + "Hello World !!!" + style.RESET
    print fore.HOT_PINK_2 + "Hello World !!!" + style.RESET
    print fore.ORCHID + "Hello World !!!" + style.RESET
    print fore.MEDIUM_ORCHID_1A + "Hello World !!!" + style.RESET
    print fore.ORANGE_3 + "Hello World !!!" + style.RESET
    print fore.LIGHT_SALMON_3B + "Hello World !!!" + style.RESET
    print fore.LIGHT_PINK_3 + "Hello World !!!" + style.RESET
    print fore.PINK_3 + "Hello World !!!" + style.RESET
    print fore.PLUM_3 + "Hello World !!!" + style.RESET
    print fore.VIOLET + "Hello World !!!" + style.RESET
    print fore.GOLD_3B + "Hello World !!!" + style.RESET
    print fore.LIGHT_GOLDENROD_3 + "Hello World !!!" + style.RESET
    print fore.TAN + "Hello World !!!" + style.RESET
    print fore.MISTY_ROSE_3 + "Hello World !!!" + style.RESET
    print fore.THISTLE_3 + "Hello World !!!" + style.RESET
    print fore.PLUM_2 + "Hello World !!!" + style.RESET
    print fore.YELLOW_3B + "Hello World !!!" + style.RESET
    print fore.KHAKI_3 + "Hello World !!!" + style.RESET
    print fore.LIGHT_GOLDENROD_2A + "Hello World !!!" + style.RESET
    print fore.LIGHT_YELLOW_3 + "Hello World !!!" + style.RESET
    print fore.GREY_84 + "Hello World !!!" + style.RESET
    print fore.LIGHT_STEEL_BLUE_1 + "Hello World !!!" + style.RESET
    print fore.YELLOW_2 + "Hello World !!!" + style.RESET
    print fore.DARK_OLIVE_GREEN_1A + "Hello World !!!" + style.RESET
    print fore.DARK_OLIVE_GREEN_1B + "Hello World !!!" + style.RESET
    print fore.DARK_SEA_GREEN_1 + "Hello World !!!" + style.RESET
    print fore.HONEYDEW_2 + "Hello World !!!" + style.RESET
    print fore.LIGHT_CYAN_1 + "Hello World !!!" + style.RESET
    print fore.RED_1 + "Hello World !!!" + style.RESET
    print fore.DEEP_PINK_2 + "Hello World !!!" + style.RESET
    print fore.DEEP_PINK_1A + "Hello World !!!" + style.RESET
    print fore.DEEP_PINK_1B + "Hello World !!!" + style.RESET
    print fore.MAGENTA_2B + "Hello World !!!" + style.RESET
    print fore.MAGENTA_1 + "Hello World !!!" + style.RESET
    print fore.ORANGE_RED_1 + "Hello World !!!" + style.RESET
    print fore.INDIAN_RED_1C + "Hello World !!!" + style.RESET
    print fore.INDIAN_RED_1D + "Hello World !!!" + style.RESET
    print fore.HOT_PINK_1A + "Hello World !!!" + style.RESET
    print fore.HOT_PINK_1B + "Hello World !!!" + style.RESET
    print fore.MEDIUM_ORCHID_1B + "Hello World !!!" + style.RESET
    print fore.DARK_ORANGE + "Hello World !!!" + style.RESET
    print fore.SALMON_1 + "Hello World !!!" + style.RESET
    print fore.LIGHT_CORAL + "Hello World !!!" + style.RESET
    print fore.PALE_VIOLET_RED_1 + "Hello World !!!" + style.RESET
    print fore.ORCHID_2 + "Hello World !!!" + style.RESET
    print fore.ORCHID_1 + "Hello World !!!" + style.RESET
    print fore.ORANGE_1 + "Hello World !!!" + style.RESET
    print fore.SANDY_BROWN + "Hello World !!!" + style.RESET
    print fore.LIGHT_SALMON_1 + "Hello World !!!" + style.RESET
    print fore.LIGHT_PINK_1 + "Hello World !!!" + style.RESET
    print fore.PINK_1 + "Hello World !!!" + style.RESET
    print fore.PLUM_1 + "Hello World !!!" + style.RESET
    print fore.GOLD_1 + "Hello World !!!" + style.RESET
    print fore.LIGHT_GOLDENROD_2B + "Hello World !!!" + style.RESET
    print fore.LIGHT_GOLDENROD_2C + "Hello World !!!" + style.RESET
    print fore.NAVAJO_WHITE_1 + "Hello World !!!" + style.RESET
    print fore.MISTY_ROSE1 + "Hello World !!!" + style.RESET
    print fore.THISTLE_1 + "Hello World !!!" + style.RESET
    print fore.YELLOW_1 + "Hello World !!!" + style.RESET
    print fore.LIGHT_GOLDENROD_1 + "Hello World !!!" + style.RESET
    print fore.KHAKI_1 + "Hello World !!!" + style.RESET
    print fore.WHEAT_1 + "Hello World !!!" + style.RESET
    print fore.CORNSILK_1 + "Hello World !!!" + style.RESET
    print fore.GREY_100 + "Hello World !!!" + style.RESET
    print fore.GREY_3 + "Hello World !!!" + style.RESET
    print fore.GREY_7 + "Hello World !!!" + style.RESET
    print fore.GREY_11 + "Hello World !!!" + style.RESET
    print fore.GREY_15 + "Hello World !!!" + style.RESET
    print fore.GREY_19 + "Hello World !!!" + style.RESET
    print fore.GREY_23 + "Hello World !!!" + style.RESET
    print fore.GREY_27 + "Hello World !!!" + style.RESET
    print fore.GREY_30 + "Hello World !!!" + style.RESET
    print fore.GREY_35 + "Hello World !!!" + style.RESET
    print fore.GREY_39 + "Hello World !!!" + style.RESET
    print fore.GREY_42 + "Hello World !!!" + style.RESET
    print fore.GREY_46 + "Hello World !!!" + style.RESET
    print fore.GREY_50 + "Hello World !!!" + style.RESET
    print fore.GREY_54 + "Hello World !!!" + style.RESET
    print fore.GREY_58 + "Hello World !!!" + style.RESET
    print fore.GREY_62 + "Hello World !!!" + style.RESET
    print fore.GREY_66 + "Hello World !!!" + style.RESET
    print fore.GREY_70 + "Hello World !!!" + style.RESET
    print fore.GREY_74 + "Hello World !!!" + style.RESET
    print fore.GREY_78 + "Hello World !!!" + style.RESET
    print fore.GREY_82 + "Hello World !!!" + style.RESET
    print fore.GREY_85 + "Hello World !!!" + style.RESET
    print fore.GREY_89 + "Hello World !!!" + style.RESET
    print fore.GREY_93 + "Hello World !!!" + style.RESET

    print back.BLACK + "Hello World !!!" + style.RESET
    print back.RED + "Hello World !!!" + style.RESET
    print back.GREEN + "Hello World !!!" + style.RESET
    print back.YELLOW + "Hello World !!!" + style.RESET
    print back.BLUE + "Hello World !!!" + style.RESET
    print back.MAGENTA + "Hello World !!!" + style.RESET
    print back.CYAN + "Hello World !!!" + style.RESET
    print back.LIGHT_GRAY + "Hello World !!!" + style.RESET
    print back.DARK_GRAY + "Hello World !!!" + style.RESET
    print back.LIGHT_RED + "Hello World !!!" + style.RESET
    print back.LIGHT_GREEN + "Hello World !!!" + style.RESET
    print back.LIGHT_YELLOW + "Hello World !!!" + style.RESET
    print back.LIGHT_BLUE + "Hello World !!!" + style.RESET
    print back.LIGHT_MAGENTA + "Hello World !!!" + style.RESET
    print back.LIGHT_CYAN + "Hello World !!!" + style.RESET
    print back.WHITE + "Hello World !!!" + style.RESET
    print back.GREY_0 + "Hello World !!!" + style.RESET
    print back.NAVY_BLUE + "Hello World !!!" + style.RESET
    print back.DARK_BLUE + "Hello World !!!" + style.RESET
    print back.BLUE_3A + "Hello World !!!" + style.RESET
    print back.BLUE_3B + "Hello World !!!" + style.RESET
    print back.BLUE_1 + "Hello World !!!" + style.RESET
    print back.DARK_GREEN + "Hello World !!!" + style.RESET
    print back.DEEP_SKY_BLUE_4A + "Hello World !!!" + style.RESET
    print back.DEEP_SKY_BLUE_4B + "Hello World !!!" + style.RESET
    print back.DEEP_SKY_BLUE_4C + "Hello World !!!" + style.RESET
    print back.DODGER_BLUE_3 + "Hello World !!!" + style.RESET
    print back.DODGER_BLUE_2 + "Hello World !!!" + style.RESET
    print back.GREEN_4 + "Hello World !!!" + style.RESET
    print back.SPRING_GREEN_4 + "Hello World !!!" + style.RESET
    print back.TURQUOISE_4 + "Hello World !!!" + style.RESET
    print back.DEEP_SKY_BLUE_3A + "Hello World !!!" + style.RESET
    print back.DEEP_SKY_BLUE_3B + "Hello World !!!" + style.RESET
    print back.DODGER_BLUE_1 + "Hello World !!!" + style.RESET
    print back.GREEN_3A + "Hello World !!!" + style.RESET
    print back.SPRING_GREEN_3A + "Hello World !!!" + style.RESET
    print back.DARK_CYAN + "Hello World !!!" + style.RESET
    print back.LIGHT_SEA_GREEN + "Hello World !!!" + style.RESET
    print back.DEEP_SKY_BLUE_2 + "Hello World !!!" + style.RESET
    print back.DEEP_SKY_BLUE_1 + "Hello World !!!" + style.RESET
    print back.GREEN_3B + "Hello World !!!" + style.RESET
    print back.SPRING_GREEN_3B + "Hello World !!!" + style.RESET
    print back.SPRING_GREEN_2A + "Hello World !!!" + style.RESET
    print back.CYAN_3 + "Hello World !!!" + style.RESET
    print back.DARK_TURQUOISE + "Hello World !!!" + style.RESET
    print back.TURQUOISE_2 + "Hello World !!!" + style.RESET
    print back.GREEN_1 + "Hello World !!!" + style.RESET
    print back.SPRING_GREEN_2B + "Hello World !!!" + style.RESET
    print back.SPRING_GREEN_1 + "Hello World !!!" + style.RESET
    print back.MEDIUM_SPRING_GREEN + "Hello World !!!" + style.RESET
    print back.CYAN_2 + "Hello World !!!" + style.RESET
    print back.CYAN_1 + "Hello World !!!" + style.RESET
    print back.DARK_RED_1 + "Hello World !!!" + style.RESET
    print back.DEEP_PINK_4A + "Hello World !!!" + style.RESET
    print back.PURPLE_4A + "Hello World !!!" + style.RESET
    print back.PURPLE_4B + "Hello World !!!" + style.RESET
    print back.PURPLE_3 + "Hello World !!!" + style.RESET
    print back.BLUE_VIOLET + "Hello World !!!" + style.RESET
    print back.ORANGE_4A + "Hello World !!!" + style.RESET
    print back.GREY_37 + "Hello World !!!" + style.RESET
    print back.MEDIUM_PURPLE_4 + "Hello World !!!" + style.RESET
    print back.SLATE_BLUE_3A + "Hello World !!!" + style.RESET
    print back.SLATE_BLUE_3B + "Hello World !!!" + style.RESET
    print back.ROYAL_BLUE_1 + "Hello World !!!" + style.RESET
    print back.CHARTREUSE_4 + "Hello World !!!" + style.RESET
    print back.DARK_SEA_GREEN_4A + "Hello World !!!" + style.RESET
    print back.PALE_TURQUOISE_4 + "Hello World !!!" + style.RESET
    print back.STEEL_BLUE + "Hello World !!!" + style.RESET
    print back.STEEL_BLUE_3 + "Hello World !!!" + style.RESET
    print back.CORNFLOWER_BLUE + "Hello World !!!" + style.RESET
    print back.CHARTREUSE_3A + "Hello World !!!" + style.RESET
    print back.DARK_SEA_GREEN_4B + "Hello World !!!" + style.RESET
    print back.CADET_BLUE_2 + "Hello World !!!" + style.RESET
    print back.CADET_BLUE_1 + "Hello World !!!" + style.RESET
    print back.SKY_BLUE_3 + "Hello World !!!" + style.RESET
    print back.STEEL_BLUE_1A + "Hello World !!!" + style.RESET
    print back.CHARTREUSE_3B + "Hello World !!!" + style.RESET
    print back.PALE_GREEN_3A + "Hello World !!!" + style.RESET
    print back.SEA_GREEN_3 + "Hello World !!!" + style.RESET
    print back.AQUAMARINE_3 + "Hello World !!!" + style.RESET
    print back.MEDIUM_TURQUOISE + "Hello World !!!" + style.RESET
    print back.STEEL_BLUE_1B + "Hello World !!!" + style.RESET
    print back.CHARTREUSE_2A + "Hello World !!!" + style.RESET
    print back.SEA_GREEN_2 + "Hello World !!!" + style.RESET
    print back.SEA_GREEN_1A + "Hello World !!!" + style.RESET
    print back.SEA_GREEN_1B + "Hello World !!!" + style.RESET
    print back.AQUAMARINE_1A + "Hello World !!!" + style.RESET
    print back.DARK_SLATE_GRAY_2 + "Hello World !!!" + style.RESET
    print back.DARK_RED_2 + "Hello World !!!" + style.RESET
    print back.DEEP_PINK_4B + "Hello World !!!" + style.RESET
    print back.DARK_MAGENTA_1 + "Hello World !!!" + style.RESET
    print back.DARK_MAGENTA_2 + "Hello World !!!" + style.RESET
    print back.DARK_VIOLET_1A + "Hello World !!!" + style.RESET
    print back.PURPLE_1A + "Hello World !!!" + style.RESET
    print back.ORANGE_4B + "Hello World !!!" + style.RESET
    print back.LIGHT_PINK_4 + "Hello World !!!" + style.RESET
    print back.PLUM_4 + "Hello World !!!" + style.RESET
    print back.MEDIUM_PURPLE_3A + "Hello World !!!" + style.RESET
    print back.MEDIUM_PURPLE_3B + "Hello World !!!" + style.RESET
    print back.SLATE_BLUE_1 + "Hello World !!!" + style.RESET
    print back.YELLOW_4A + "Hello World !!!" + style.RESET
    print back.WHEAT_4 + "Hello World !!!" + style.RESET
    print back.GREY_53 + "Hello World !!!" + style.RESET
    print back.LIGHT_SLATE_GREY + "Hello World !!!" + style.RESET
    print back.MEDIUM_PURPLE + "Hello World !!!" + style.RESET
    print back.LIGHT_SLATE_BLUE + "Hello World !!!" + style.RESET
    print back.YELLOW_4B + "Hello World !!!" + style.RESET
    print back.DARK_OLIVE_GREEN_3A + "Hello World !!!" + style.RESET
    print back.DARK_GREEN_SEA + "Hello World !!!" + style.RESET
    print back.LIGHT_SKY_BLUE_3A + "Hello World !!!" + style.RESET
    print back.LIGHT_SKY_BLUE_3B + "Hello World !!!" + style.RESET
    print back.SKY_BLUE_2 + "Hello World !!!" + style.RESET
    print back.CHARTREUSE_2B + "Hello World !!!" + style.RESET
    print back.DARK_OLIVE_GREEN_3B + "Hello World !!!" + style.RESET
    print back.PALE_GREEN_3B + "Hello World !!!" + style.RESET
    print back.DARK_SEA_GREEN_3A + "Hello World !!!" + style.RESET
    print back.DARK_SLATE_GRAY_3 + "Hello World !!!" + style.RESET
    print back.SKY_BLUE_1 + "Hello World !!!" + style.RESET
    print back.CHARTREUSE_1 + "Hello World !!!" + style.RESET
    print back.LIGHT_GREEN_2 + "Hello World !!!" + style.RESET
    print back.LIGHT_GREEN_3 + "Hello World !!!" + style.RESET
    print back.PALE_GREEN_1A + "Hello World !!!" + style.RESET
    print back.AQUAMARINE_1B + "Hello World !!!" + style.RESET
    print back.DARK_SLATE_GRAY_1 + "Hello World !!!" + style.RESET
    print back.RED_3A + "Hello World !!!" + style.RESET
    print back.DEEP_PINK_4C + "Hello World !!!" + style.RESET
    print back.MEDIUM_VIOLET_RED + "Hello World !!!" + style.RESET
    print back.MAGENTA_3A + "Hello World !!!" + style.RESET
    print back.DARK_VIOLET_1B + "Hello World !!!" + style.RESET
    print back.PURPLE_1B + "Hello World !!!" + style.RESET
    print back.DARK_ORANGE_3A + "Hello World !!!" + style.RESET
    print back.INDIAN_RED_1A + "Hello World !!!" + style.RESET
    print back.HOT_PINK_3A + "Hello World !!!" + style.RESET
    print back.MEDIUM_ORCHID_3 + "Hello World !!!" + style.RESET
    print back.MEDIUM_ORCHID + "Hello World !!!" + style.RESET
    print back.MEDIUM_PURPLE_2A + "Hello World !!!" + style.RESET
    print back.DARK_GOLDENROD + "Hello World !!!" + style.RESET
    print back.LIGHT_SALMON_3A + "Hello World !!!" + style.RESET
    print back.ROSY_BROWN + "Hello World !!!" + style.RESET
    print back.GREY_63 + "Hello World !!!" + style.RESET
    print back.MEDIUM_PURPLE_2B + "Hello World !!!" + style.RESET
    print back.MEDIUM_PURPLE_1 + "Hello World !!!" + style.RESET
    print back.GOLD_3A + "Hello World !!!" + style.RESET
    print back.DARK_KHAKI + "Hello World !!!" + style.RESET
    print back.NAVAJO_WHITE_3 + "Hello World !!!" + style.RESET
    print back.GREY_69 + "Hello World !!!" + style.RESET
    print back.LIGHT_STEEL_BLUE_3 + "Hello World !!!" + style.RESET
    print back.LIGHT_STEEL_BLUE + "Hello World !!!" + style.RESET
    print back.YELLOW_3A + "Hello World !!!" + style.RESET
    print back.DARK_OLIVE_GREEN_3 + "Hello World !!!" + style.RESET
    print back.DARK_SEA_GREEN_3B + "Hello World !!!" + style.RESET
    print back.DARK_SEA_GREEN_2 + "Hello World !!!" + style.RESET
    print back.LIGHT_CYAN_3 + "Hello World !!!" + style.RESET
    print back.LIGHT_SKY_BLUE_1 + "Hello World !!!" + style.RESET
    print back.GREEN_YELLOW + "Hello World !!!" + style.RESET
    print back.DARK_OLIVE_GREEN_2 + "Hello World !!!" + style.RESET
    print back.PALE_GREEN_1B + "Hello World !!!" + style.RESET
    print back.DARK_SEA_GREEN_5B + "Hello World !!!" + style.RESET
    print back.DARK_SEA_GREEN_5A + "Hello World !!!" + style.RESET
    print back.PALE_TURQUOISE_1 + "Hello World !!!" + style.RESET
    print back.RED_3A + "Hello World !!!" + style.RESET
    print back.DEEP_PINK_3A + "Hello World !!!" + style.RESET
    print back.DEEP_PINK_3B + "Hello World !!!" + style.RESET
    print back.MAGENTA_3B + "Hello World !!!" + style.RESET
    print back.MAGENTA_3C + "Hello World !!!" + style.RESET
    print back.MAGENTA_2A + "Hello World !!!" + style.RESET
    print back.DARK_ORANGE_3B + "Hello World !!!" + style.RESET
    print back.INDIAN_RED_1B + "Hello World !!!" + style.RESET
    print back.HOT_PINK_3B + "Hello World !!!" + style.RESET
    print back.HOT_PINK_2 + "Hello World !!!" + style.RESET
    print back.ORCHID + "Hello World !!!" + style.RESET
    print back.MEDIUM_ORCHID_1A + "Hello World !!!" + style.RESET
    print back.ORANGE_3 + "Hello World !!!" + style.RESET
    print back.LIGHT_SALMON_3B + "Hello World !!!" + style.RESET
    print back.LIGHT_PINK_3 + "Hello World !!!" + style.RESET
    print back.PINK_3 + "Hello World !!!" + style.RESET
    print back.PLUM_3 + "Hello World !!!" + style.RESET
    print back.VIOLET + "Hello World !!!" + style.RESET
    print back.GOLD_3B + "Hello World !!!" + style.RESET
    print back.LIGHT_GOLDENROD_3 + "Hello World !!!" + style.RESET
    print back.TAN + "Hello World !!!" + style.RESET
    print back.MISTY_ROSE_3 + "Hello World !!!" + style.RESET
    print back.THISTLE_3 + "Hello World !!!" + style.RESET
    print back.PLUM_2 + "Hello World !!!" + style.RESET
    print back.YELLOW_3B + "Hello World !!!" + style.RESET
    print back.KHAKI_3 + "Hello World !!!" + style.RESET
    print back.LIGHT_GOLDENROD_2A + "Hello World !!!" + style.RESET
    print back.LIGHT_YELLOW_3 + "Hello World !!!" + style.RESET
    print back.GREY_84 + "Hello World !!!" + style.RESET
    print back.LIGHT_STEEL_BLUE_1 + "Hello World !!!" + style.RESET
    print back.YELLOW_2 + "Hello World !!!" + style.RESET
    print back.DARK_OLIVE_GREEN_1A + "Hello World !!!" + style.RESET
    print back.DARK_OLIVE_GREEN_1B + "Hello World !!!" + style.RESET
    print back.DARK_SEA_GREEN_1 + "Hello World !!!" + style.RESET
    print back.HONEYDEW_2 + "Hello World !!!" + style.RESET
    print back.LIGHT_CYAN_1 + "Hello World !!!" + style.RESET
    print back.RED_1 + "Hello World !!!" + style.RESET
    print back.DEEP_PINK_2 + "Hello World !!!" + style.RESET
    print back.DEEP_PINK_1A + "Hello World !!!" + style.RESET
    print back.DEEP_PINK_1B + "Hello World !!!" + style.RESET
    print back.MAGENTA_2B + "Hello World !!!" + style.RESET
    print back.MAGENTA_1 + "Hello World !!!" + style.RESET
    print back.ORANGE_RED_1 + "Hello World !!!" + style.RESET
    print back.INDIAN_RED_1C + "Hello World !!!" + style.RESET
    print back.INDIAN_RED_1D + "Hello World !!!" + style.RESET
    print back.HOT_PINK_1A + "Hello World !!!" + style.RESET
    print back.HOT_PINK_1B + "Hello World !!!" + style.RESET
    print back.MEDIUM_ORCHID_1B + "Hello World !!!" + style.RESET
    print back.DARK_ORANGE + "Hello World !!!" + style.RESET
    print back.SALMON_1 + "Hello World !!!" + style.RESET
    print back.LIGHT_CORAL + "Hello World !!!" + style.RESET
    print back.PALE_VIOLET_RED_1 + "Hello World !!!" + style.RESET
    print back.ORCHID_2 + "Hello World !!!" + style.RESET
    print back.ORCHID_1 + "Hello World !!!" + style.RESET
    print back.ORANGE_1 + "Hello World !!!" + style.RESET
    print back.SANDY_BROWN + "Hello World !!!" + style.RESET
    print back.LIGHT_SALMON_1 + "Hello World !!!" + style.RESET
    print back.LIGHT_PINK_1 + "Hello World !!!" + style.RESET
    print back.PINK_1 + "Hello World !!!" + style.RESET
    print back.PLUM_1 + "Hello World !!!" + style.RESET
    print back.GOLD_1 + "Hello World !!!" + style.RESET
    print back.LIGHT_GOLDENROD_2B + "Hello World !!!" + style.RESET
    print back.LIGHT_GOLDENROD_2C + "Hello World !!!" + style.RESET
    print back.NAVAJO_WHITE_1 + "Hello World !!!" + style.RESET
    print back.MISTY_ROSE1 + "Hello World !!!" + style.RESET
    print back.THISTLE_1 + "Hello World !!!" + style.RESET
    print back.YELLOW_1 + "Hello World !!!" + style.RESET
    print back.LIGHT_GOLDENROD_1 + "Hello World !!!" + style.RESET
    print back.KHAKI_1 + "Hello World !!!" + style.RESET
    print back.WHEAT_1 + "Hello World !!!" + style.RESET
    print back.CORNSILK_1 + "Hello World !!!" + style.RESET
    print back.GREY_100 + "Hello World !!!" + style.RESET
    print back.GREY_3 + "Hello World !!!" + style.RESET
    print back.GREY_7 + "Hello World !!!" + style.RESET
    print back.GREY_11 + "Hello World !!!" + style.RESET
    print back.GREY_15 + "Hello World !!!" + style.RESET
    print back.GREY_19 + "Hello World !!!" + style.RESET
    print back.GREY_23 + "Hello World !!!" + style.RESET
    print back.GREY_27 + "Hello World !!!" + style.RESET
    print back.GREY_30 + "Hello World !!!" + style.RESET
    print back.GREY_35 + "Hello World !!!" + style.RESET
    print back.GREY_39 + "Hello World !!!" + style.RESET
    print back.GREY_42 + "Hello World !!!" + style.RESET
    print back.GREY_46 + "Hello World !!!" + style.RESET
    print back.GREY_50 + "Hello World !!!" + style.RESET
    print back.GREY_54 + "Hello World !!!" + style.RESET
    print back.GREY_58 + "Hello World !!!" + style.RESET
    print back.GREY_62 + "Hello World !!!" + style.RESET
    print back.GREY_66 + "Hello World !!!" + style.RESET
    print back.GREY_70 + "Hello World !!!" + style.RESET
    print back.GREY_74 + "Hello World !!!" + style.RESET
    print back.GREY_78 + "Hello World !!!" + style.RESET
    print back.GREY_82 + "Hello World !!!" + style.RESET
    print back.GREY_85 + "Hello World !!!" + style.RESET
    print back.GREY_89 + "Hello World !!!" + style.RESET
    print back.GREY_93 + "Hello World !!!" + style.RESET


if __name__ == "__main__":
    main()
